# Generated by Django 4.0.1 on 2022-05-12 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id categoria')),
                ('nombreCategoria', models.CharField(max_length=20, verbose_name='Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUsuario', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id Usuario')),
                ('nombreUsuario', models.CharField(max_length=50, verbose_name='Nombre Usuario')),
                ('contraUsuario', models.CharField(max_length=10, verbose_name='Contraseña')),
            ],
        ),
    ]
