# Generated by Django 4.0.1 on 2022-05-12 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_empanadas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empanadas',
            old_name='Categoria',
            new_name='categoria',
        ),
        migrations.RenameField(
            model_name='empanadas',
            old_name='tipoPan',
            new_name='tipoEmpanada',
        ),
        migrations.RenameField(
            model_name='panes',
            old_name='Categoria',
            new_name='categoria',
        ),
    ]
