# Generated by Django 4.0.1 on 2022-05-19 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_categoria_empanadas_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='email',
            field=models.CharField(default='no', max_length=50, verbose_name='Email'),
        ),
    ]
