# Generated by Django 4.0.1 on 2022-05-26 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_usuario_idusuario_alter_usuario_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='nombreProducto',
            field=models.CharField(max_length=30, verbose_name='Nombre producto'),
        ),
    ]
